modLoader = "javafml"
loaderVersion = "[4,)"
license = "Polyform-Shield-1.0.0"

[[mods]]
modId = "sodium"

version = "${version}"
displayName = "Vuldium"

iconFile = "sodium-icon.png" #optional

authors = "JellySquid (jellysquid3), IMS212"

credits = "bytzo, PepperCode1, FlashyReese, altrisi, Grayray75, Madis0, Johni0702, comp500, coderbot16, Moulberry, MCRcortex, Altirix, embeddedt, pajicadvance, Kroppeb, douira, burgerindividual, TwistedZero, Leo40Git, haykam821, muzikbike"

description = '''
Vuldium is a next-generation Vulkan rendering engine for Minecraft featuring Hardware GPU Culling, Translucent Sorting, and Multi-AI Upscaling (DLSS/FSR/XeSS).
'''

[modproperties.sodium]
"fabric-renderer-api-v1:contains_renderer" = true
"fabric:provides" = ["indium"]

[[mixins]]
config = "sodium-common.mixins.json"

[[mixins]]
config = "sodium-neoforge.mixins.json"

[[dependencies.sodium]]
modId = "neoforge"
type = "required"
versionRange = "[26.1.0,)"
ordering = "NONE"
side = "BOTH"
